name: RedeemPlugin
version: 1.0
main: com.example.RedeemPlugin
author: devbrius
description: A plugin for redeeming codes and granting PlayerPoints.
commands:
  redeem:
    description: Redeem a code for PlayerPoints.
    usage: /redeem <code>
  redeemhelp:
    description: Display plugin commands and usage.
  redeemreload:
    description: Reload the plugin configuration.
permissions:
  redeem.use:
    description: Allows players to use the redeem command.
    default: true
