# Plugin made by devbrius
# Discord: devbrius
# Github: https://github.com/briusxD/Redeem
# Language option Turkish "tr", English "en"
locale: tr

# codes option "1250:ABCDEFGHI" or "ABCDEFGHI:1250"
codes:
  '1250':
    - ABCDEFGHI
    - JKLMNOPQR
  '750':
    - STUVWXYZA
    - XYZ123456
  '500':
    - ABC987654
  '250':
    - CODE001
  '100':
    - CODE003
  CODE003: 100
  STUVWXYZA: 750
  XYZ123456: 750
  ABC987654: 500
  ABCDEFGHI: 1250
  JKLMNOPQR: 1250
  CODE001: 250

# used codes list in here
used_codes: []
